### ISSUE TITLE
VBlank Issues when the screen is turned off/on (screen lock, suspend & resume)

### ISSUE THREAD

**Issue by spacekookie** [M-Bab/linux-kernel-amdgpu-binaries#29]
I'm running Ubuntu 16.04 and I can't suspend my computer with this kernel. My Computer

CPU: Ryzen R7 1700
GPU: RX Vega 64
Motherboard: Asus PRIME X370-A

The suspend issues only appeared with my new GPU and me thus using this Kernel. Any logs you would want me to post to help debug this?

**Comment by mezcalbert** [comment]
I have the same issue (or a similar one at least) with my Baffin card (RX 560) on Ubuntu 17.04. At some random and quite frequent times the system won't wake up from suspend.

Sometimes it will wake up from a 6 day suspend, and sometimes the system is frozen after a light suspend of an hour, or the other way around. It happens ever since I tried this modified kernel, around 4.11.7+, and through 4.13.1+ or all the in betweens.

I don't want to go back to 4.9 as there were a lot of improvements with regard to performance in the meantime and booting again isn't that big of an issue with an SSD. Still, all the open apps have to be reopened.

**Comment by M-Bab** [comment]
Can confirm the issues reported on suspend/resume issues. Hopefully it gets better when I build 4.13 end of this week. Otherwise I will try to git bisect the issue and report it to the AMD developers.

**Comment by nukedathlonman** [comment]
Well, different graphics altogether, and I'm unsure where to send info to...  I have an HP Pavilion A10-8700 HP notebook ("Carrizo" APU - so CGN 1.2+ (Volcanic Islands) based Radeon R6 Integrated iGPU that uses system memory (I know, yuck... ;-) ), and suspend/resume is failing on it as well.  I did a little debugging using pm-trace (oh, I'm using Kubuntu 16.04.3 with your current kernel 4.12.14+ 17.09.20), and then looking at the dmesg output after a power off and off (after attempting to resume).

Symptom: computer goes into suspend state with blinking power led, on resume (hit button or flip up screen) notebook turns on, but the screen doesn't turn on, no response from keyboard with caps/numlock/scrollock led's - system appears to be hard locked and can't SSH into it - requires a full power down).

The relevant dmesg output is:

[    2.021036]   Magic number: 0:268:508
[    2.021041]   hash matches drivers/base/power/main.c:801
[    2.021147] pci  0000:00:01.0: hash matches

The relevant line from lspci:

00:01.0 VGA compatible controller: Advanced Microdevices, Inc.  [AMD/ATI] Carrizo (rev c5)

I still have further debugging to do.  All I've determined is that the failure point appears to be graphics related.

**Comment by M-Bab** [comment]
Unfortunately this issue is not yet resolved in 4.13.5+. But I cought a "nice" kernel crash+trace which I will report the AMD Devs. Can you confirm that this issue can occur not only when resuming from suspend but also when the display is re-activated after the screen was locked?

Does the system hang for you on
a.) a black screen?
b.) a screen with weird pattern?
c.) the login screen?

Did you notice the last kernel where this problem did not exist? So do you know at which kernel version the problem was introduced exactly?

**Comment by nukedathlonman** [comment]
I'm not home right now, but will do the traces as soon as possible.  On resume, the display doesn't power up at all (so back with no backlight).  No led's light up when one presses the caps/num lock keys.  No network connectivity at all (wired or wirless).  The only led that is solid is the power indicator.  The pm-trace I ran indicates a failure with the AMDGPU driver when I manually hardpower down and the power it back up while pm-trace is active (why I gave the clippings from dmesg and lsmod).  Other then that, I haven't run into any other show stopper issue.  Fact, the notebook I know right now has an uptime of 5 days and has had signifigantly longer up time periods (I know it crazy to operate a low power notebook 24-7 operation).  No issues with shutting the lid (setup to just turn off the display, not sleep when on hydro).  The last fully working Kernel (everything worked no issue, including suspend, resume, etc) would go all the way back to Kubuntu 15.10, but I was using the very last closed Catylist blob.  All kernels I've tested with amdgpu by it self (so no DAL/DC) is beyond unstable on this system.  No DC means all sorts of glitches, the worst being the entire graphics system would ramdomly kick out, although sshing into the system one could shut it down unlike trying to resume.  With DC (I started with your 4.9.5 kernel) it works properly, like in Kubuntu 15.10 with Catalyst (except for this suspend/resume issue).  Lock screen works fine for me (even after shutting the lid and haveing the display turn off).  Not sure if this is of help, but I am using Pakdoka's Messa PPA (and OpenCL and radv are working).
________________________________

**Comment by DarkFoss** [comment]
Your 4.13.5+ Ubuntu is actually much stabler than Ubuntu's stock on 17.10. Only 2 Call Traces during start-up both appear to be freesync related like it's trying to apply to my monitor which doesn't support it. 
Only issue I have coming out of sleep is the random failure of my second card to initialize. I've seen A and B but not with this kernel.
I could attach the Call Backs if you'd like but Michael rolled an updated 4.13 kernel this morning with the
4.15-drm-next-dc. So far with all that code clean-up they are gone and it seems to be even stabler than the staging-drm-next line with my hardware which is quite promising.
All in all nice work M-Bab Thanks again for making this available.

**Comment by M-Bab** [comment]
@DarkFoss I am already planning to test 4.15-drm-next-dc as well. So far I could hardly see any difference in commits to amd-staging-drm-next. The latter even felt to be updated more often. Do you have any details what is more stable? Does 4.15-drm-next-dc resolve the suspend/wakeup issue?

**Comment by DarkFoss** [comment]
@M-Bab Artful had a system.d update along with other system related packages. I've been re-testing yours since and to be honest I haven't been able to trigger any S3 failures, of course I had forgotten to turn off fast boot after doing some windows maintanence lol. The dc kernel is a bit more stable with my older monitor less out of sync issues and better chance of recovery when it does happen, also shows a system.d message related to S3 that this or the stock kernel doesn't show..I'll post it when I find it again might help point out whats going on with S3 in general with the whole 4.13 line.
Anyways here's the freesync error that appears 2x during boot and once upon resume harmless to me but anyone with a freesync monitor might be experience problems if triggered. 
```
[ 3053.726366] [drm] DCHPD: connector_id=0: Old sink=          (null) New sink=ffff9c5ac0e5fc00
[ 3053.726794] ------------[ cut here ]------------
[ 3053.726801] WARNING: CPU: 0 PID: 4261 at drivers/gpu/drm/drm_mode_object.c:237 drm_object_property_set_value+0x57/0x70 [drm]
[ 3053.726802] Modules linked in: binfmt_misc nls_iso8859_1 edac_mce_amd snd_hda_codec_realtek snd_hda_codec_generic kvm_amd snd_hda_codec_hdmi kvm joydev eeepc_wmi asus_wmi irqbypass sparse_keymap video wmi_bmof input_leds snd_hda_intel snd_hda_codec fam15h_power k10temp snd_hda_core snd_hwdep i2c_piix4 snd_pcm snd_seq_midi snd_seq_midi_event snd_rawmidi snd_seq snd_seq_device snd_timer snd soundcore shpchp tpm_infineon mac_hid parport_pc ppdev lp parport ip_tables x_tables autofs4 algif_skcipher af_alg dm_crypt hid_generic usbhid hid amdkfd amd_iommu_v2 crct10dif_pclmul crc32_pclmul amdgpu ghash_clmulni_intel pcbc mxm_wmi aesni_intel chash aes_x86_64 i2c_algo_bit crypto_simd ttm glue_helper cryptd drm_kms_helper syscopyarea sysfillrect e1000e sysimgblt fb_sys_fops drm ahci ptp libahci pps_core wmi
[ 3053.726821] CPU: 0 PID: 4261 Comm: kworker/u16:63 Tainted: G        W       4.13.5+ #1
[ 3053.726822] Hardware name: To be filled by O.E.M. To be filled by O.E.M./CROSSHAIR V FORMULA-Z, BIOS 2201 03/23/2015
[ 3053.726824] Workqueue: events_unbound async_run_entry_fn
[ 3053.726825] task: ffff9c5aca4c8000 task.stack: ffffac6dc4d5c000
[ 3053.726830] RIP: 0010:drm_object_property_set_value+0x57/0x70 [drm]
[ 3053.726830] RSP: 0018:ffffac6dc4d5fc68 EFLAGS: 00010246
[ 3053.726831] RAX: ffffffffc05b24a0 RBX: ffff9c5ac0f1d000 RCX: ffff9c5ac0f1d1a0
[ 3053.726832] RDX: 0000000000000000 RSI: ffff9c5abfcdec00 RDI: ffff9c5ac0f1d028
[ 3053.726832] RBP: ffffac6dc4d5fc68 R08: ffff9c5ac0f1d148 R09: ffffffffc0512882
[ 3053.726833] R10: ffffe701512a00c0 R11: 0000000000000001 R12: 0000000000000000
[ 3053.726833] R13: ffff9c5ac1360000 R14: ffff9c5ac0f1d028 R15: ffff9c5ac0f1dd28
[ 3053.726834] FS:  0000000000000000(0000) GS:ffff9c5adfc00000(0000) knlGS:0000000000000000
[ 3053.726835] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 3053.726835] CR2: 00007fc678b5c000 CR3: 00000003f6dd7000 CR4: 00000000000406f0
[ 3053.726836] Call Trace:
[ 3053.726872]  amdgpu_dm_add_sink_to_freesync_module+0x8d/0x1b0 [amdgpu]
[ 3053.726897]  amdgpu_dm_update_connector_after_detect+0xb9/0x210 [amdgpu]
[ 3053.726920]  amdgpu_dm_display_resume+0x12b/0x140 [amdgpu]
[ 3053.726944]  amdgpu_device_resume+0x287/0x3c0 [amdgpu]
[ 3053.726966]  amdgpu_pmops_resume+0x53/0x60 [amdgpu]
[ 3053.726968]  pci_pm_resume+0x64/0xa0
[ 3053.726970]  dpm_run_callback+0x56/0x140
[ 3053.726971]  ? pci_pm_freeze+0xf0/0xf0
[ 3053.726973]  device_resume+0xe1/0x1f0
[ 3053.726974]  async_resume+0x1d/0x50
[ 3053.726975]  async_run_entry_fn+0x36/0x150
[ 3053.726976]  process_one_work+0x1e9/0x3f0
[ 3053.726977]  worker_thread+0x4b/0x410
[ 3053.726978]  kthread+0x109/0x140
[ 3053.726979]  ? process_one_work+0x3f0/0x3f0
[ 3053.726980]  ? kthread_create_on_node+0x70/0x70
[ 3053.726981]  ret_from_fork+0x25/0x30
[ 3053.726982] Code: 38 85 ff 7e 24 49 3b 70 08 74 24 49 8d 48 10 31 c0 eb 0a 48 83 c1 08 48 3b 71 f8 74 14 83 c0 01 39 f8 75 ef b8 ea ff ff ff 5d c3 <0f> ff eb c6 31 c0 48 98 49 89 94 c0 c8 00 00 00 31 c0 5d c3 0f 
[ 3053.726994] ---[ end trace ddfce697f620f860 ]---
[ 3053.727007] [drm] link=1, dc_sink_in=          (null) is now Disconnected
[ 3053.727008] [drm] DCHPD: connector_id=1: dc_sink didn't change.
[ 3053.727019] [drm] link=2, dc_sink_in=          (null) is now Disconnected
[ 3053.727019] [drm] DCHPD: connector_id=2: dc_sink didn't change.
[ 3053.727031] [drm] link=3, dc_sink_in=          (null) is now Disconnected
[ 3053.727031] [drm] DCHPD: connector_id=3: dc_sink didn't change.
[ 3053.727061] [drm] Atomic commit: RESET. crtc id 0:[ffff9c5abfcf7800]
```

**Edit**
One other thing on Artful gnome-tweaks wasn't installed, by default 1 setting was left under Power "Suspend when laptop lid is closed".  Of course the default was on, and when I turned it off some script described as a workaround became visable set for start-up. The script is gone now replaced by the latest  round of updates. I'm sure it had something to do with my sudden stability as much as the 1st to things I mentioned.

**Comment by M-Bab** [comment]
For me the problem persists (even with the latest kernel) with either standby or screen lock. In any case the GPU is set to blank/off and needs to enable the output again (not sure which of these steps are the actual cause). The AMD Devs are informed but very busy at the moment.

**Comment by M-Bab** [comment]
Here my syslog for reference:

Oct  6 17:52:45 Main-PC kernel: [   88.605940] BUG: unable to handle kernel NULL pointer dereference at           (null)
Oct  6 17:52:45 Main-PC kernel: [   88.606042] IP: dce110_vblank_set+0x59/0xb0 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606047] PGD 0 
Oct  6 17:52:45 Main-PC kernel: [   88.606049] P4D 0 
Oct  6 17:52:45 Main-PC kernel: [   88.606052] 
Oct  6 17:52:45 Main-PC kernel: [   88.606059] Oops: 0000 [#1] SMP
Oct  6 17:52:45 Main-PC kernel: [   88.606064] Modules linked in: rfcomm bnep binfmt_misc intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel dm_crypt kvm irqbypass crct10dif_pclmul crc32_pclmul 
ghash_clmulni_intel pcbc snd_seq_midi snd_seq_midi_event aesni_intel aes_x86_64 crypto_simd glue_helper cryptd snd_hda_codec_realtek intel_cstate intel_rapl_perf snd_hda_codec_generic snd_rawmidi snd_hda_codec_h
dmi snd_seq input_leds snd_hda_intel joydev serio_raw snd_hda_codec snd_hda_core snd_hwdep snd_seq_device snd_pcm snd_timer btusb snd btrtl soundcore mei_me shpchp mei hci_uart btbcm serdev btqca btintel bluetoo
th ecdh_generic intel_lpss_acpi intel_lpss mac_hid acpi_als tpm_infineon kfifo_buf acpi_pad industrialio parport_pc ppdev lp parport ip_tables x_tables autofs4 hid_generic uas usb_storage usbhid amdkfd amd_iommu
_v2
Oct  6 17:52:45 Main-PC kernel: [   88.606147]  amdgpu chash i2c_algo_bit ttm drm_kms_helper e1000e syscopyarea sysfillrect sysimgblt fb_sys_fops ptp r8169 pps_core drm mii ahci libahci wmi pinctrl_sunrisepoint 
video i2c_hid pinctrl_intel hid
Oct  6 17:52:45 Main-PC kernel: [   88.606175] CPU: 6 PID: 1489 Comm: xfwm4 Tainted: G        W       4.13.5+ #1
Oct  6 17:52:45 Main-PC kernel: [   88.606178] Hardware name: Gigabyte Technology Co., Ltd. B250-HD3P/B250-HD3P-CF, BIOS F3 12/07/2016
Oct  6 17:52:45 Main-PC kernel: [   88.606182] task: ffff8a625429b900 task.stack: ffffae59c2fdc000
Oct  6 17:52:45 Main-PC kernel: [   88.606244] RIP: 0010:dce110_vblank_set+0x59/0xb0 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606247] RSP: 0018:ffffae59c2fdfb28 EFLAGS: 00010086
Oct  6 17:52:45 Main-PC kernel: [   88.606251] RAX: ffff8a623fe00000 RBX: 0000000000000001 RCX: 0000000000000000
Oct  6 17:52:45 Main-PC kernel: [   88.606254] RDX: 0000000000000000 RSI: 0000000000000002 RDI: 0000000000000000
Oct  6 17:52:45 Main-PC kernel: [   88.606256] RBP: ffffae59c2fdfb50 R08: 0000000000000000 R09: 0000000000000000
Oct  6 17:52:45 Main-PC kernel: [   88.606259] R10: fffffffffffffff2 R11: 00000000fffffff2 R12: ffff8a6250d79c80
Oct  6 17:52:45 Main-PC kernel: [   88.606261] R13: ffff8a626bc18600 R14: ffffffffc04551e0 R15: ffff8a62508a4000
Oct  6 17:52:45 Main-PC kernel: [   88.606265] FS:  00007f5018552a80(0000) GS:ffff8a626ed80000(0000) knlGS:0000000000000000
Oct  6 17:52:45 Main-PC kernel: [   88.606268] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Oct  6 17:52:45 Main-PC kernel: [   88.606271] CR2: 0000000000000000 CR3: 00000004180c9000 CR4: 00000000003406e0
Oct  6 17:52:45 Main-PC kernel: [   88.606274] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Oct  6 17:52:45 Main-PC kernel: [   88.606277] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Oct  6 17:52:45 Main-PC kernel: [   88.606279] Call Trace:
Oct  6 17:52:45 Main-PC kernel: [   88.606341]  dal_irq_service_set+0x6f/0x90 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606399]  dc_interrupt_set+0x24/0x30 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606473]  amdgpu_dm_set_crtc_irq_state+0x35/0x60 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606532]  amdgpu_irq_update+0x55/0xa0 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606588]  amdgpu_irq_get+0x49/0x60 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606629]  amdgpu_enable_vblank_kms+0x27/0x30 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606645]  drm_vblank_enable+0x84/0x100 [drm]
Oct  6 17:52:45 Main-PC kernel: [   88.606658]  drm_vblank_get+0x92/0xb0 [drm]
Oct  6 17:52:45 Main-PC kernel: [   88.606670]  drm_wait_vblank_ioctl+0xba/0x5b0 [drm]
Oct  6 17:52:45 Main-PC kernel: [   88.606677]  ? import_iovec+0x3a/0xe0
Oct  6 17:52:45 Main-PC kernel: [   88.606684]  ? unix_stream_recvmsg+0x54/0x70
Oct  6 17:52:45 Main-PC kernel: [   88.606690]  ? unix_state_double_lock+0x70/0x70
Oct  6 17:52:45 Main-PC kernel: [   88.606702]  ? drm_legacy_modeset_ctl_ioctl+0x100/0x100 [drm]
Oct  6 17:52:45 Main-PC kernel: [   88.606715]  drm_ioctl_kernel+0x69/0xb0 [drm]
Oct  6 17:52:45 Main-PC kernel: [   88.606727]  drm_ioctl+0x33c/0x3f0 [drm]
Oct  6 17:52:45 Main-PC kernel: [   88.606738]  ? drm_legacy_modeset_ctl_ioctl+0x100/0x100 [drm]
Oct  6 17:52:45 Main-PC kernel: [   88.606780]  amdgpu_drm_ioctl+0x4f/0x90 [amdgpu]
Oct  6 17:52:45 Main-PC kernel: [   88.606787]  do_vfs_ioctl+0xa3/0x610
Oct  6 17:52:45 Main-PC kernel: [   88.606792]  ? __sys_recvmsg+0x51/0x90
Oct  6 17:52:45 Main-PC kernel: [   88.606795]  ? __sys_recvmsg+0x51/0x90
Oct  6 17:52:45 Main-PC kernel: [   88.606802]  SyS_ioctl+0x79/0x90
Oct  6 17:52:45 Main-PC kernel: [   88.606806]  entry_SYSCALL_64_fastpath+0x1e/0xa9
Oct  6 17:52:45 Main-PC kernel: [   88.606810] RIP: 0033:0x7f5014c6d587
Oct  6 17:52:45 Main-PC kernel: [   88.606813] RSP: 002b:00007ffe34170958 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
Oct  6 17:52:45 Main-PC kernel: [   88.606817] RAX: ffffffffffffffda RBX: 0000562aec72b650 RCX: 00007f5014c6d587
Oct  6 17:52:45 Main-PC kernel: [   88.606820] RDX: 00007ffe341709d0 RSI: 00000000c018643a RDI: 0000000000000006
Oct  6 17:52:45 Main-PC kernel: [   88.606822] RBP: 00007ffe34170864 R08: 00000000006001e5 R09: 0000000000000000
Oct  6 17:52:45 Main-PC kernel: [   88.606825] R10: 00007ffe34170910 R11: 0000000000000246 R12: 0000562aec72b668
Oct  6 17:52:45 Main-PC kernel: [   88.606827] R13: 00007ffe34170868 R14: 0000000000000001 R15: 00007ffe34170770
Oct  6 17:52:45 Main-PC kernel: [   88.606831] Code: 84 db 74 34 83 e8 4e be 02 00 00 00 0f b6 d0 48 89 d0 48 c1 e0 04 48 29 d0 48 c1 e0 06 49 03 87 38 01 00 00 48 8b b8 68 02 00 00 <48> 8b 07 ff 90 d8 00 00 00 84 c0 74 1e 0f b6 d3 4c 89 f6 4c 89 
Oct  6 17:52:45 Main-PC kernel: [   88.606954] RIP: dce110_vblank_set+0x59/0xb0 [amdgpu] RSP: ffffae59c2fdfb28
Oct  6 17:52:45 Main-PC kernel: [   88.606957] CR2: 0000000000000000
Oct  6 17:52:45 Main-PC kernel: [   88.606961] ---[ end trace afd0d6685dd56a18 ]---
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@

**Comment by DarkFoss** [comment]
Apport just captured an S3 related event on 17.10's official kernel 4.13.0-16-generic. Hopefully the auto generated report will help get this issue resolved in the future.

**Comment by M-Bab** [comment]
@DarkFoss So this issue (not resuming/recovering from gpu off) also exists in the official 4.13 kernel?!

**Comment by mezcalbert** [comment]
Installed 4.14.0+ yesterday. Booted into it right after. Working as it should.
But then...

First suspend yesterday. First system black out on resume today.. :-(.

**Comment by mezcalbert** [comment]
Not one successful resume with this one. This is worse than before.
I will now use mainline kernel daily builds as amdgpu dc has been merged. I would have waited another week for 4.15-rc1 but I really hate to shut down and restart every day. Hopefully, the issue will be sorted out in 4.15.

**Comment by M-Bab** [comment]
@mezcalbert I am also looking forward to 4.15 where I expect things to be more stable and my little efforts will be not required anymore.

I am equally unhappy about this bug and I also warned on the update notifications. Overall I reported the bug 3 times to the AMD developers:
https://lists.freedesktop.org/archives/amd-gfx/2017-October/014041.html
https://lists.freedesktop.org/archives/amd-gfx/2017-November/015480.html
https://lists.freedesktop.org/archives/amd-gfx/2017-November/016236.html
Last time today with more debugging info so there is fair hope that the regression will be fixed. It would be aweful if this reaches the 4.15 kernel.

**Comment by mezcalbert** [comment]
Hi Martin,
Maybe it wasn't obvious on my previous messagesbut Iwant to make clear that you did a tremendously good work and I'm very well aware that this bug is not up to you. Hopefully, with the merge of dc in 4.15 you should be relieved of the maintenance of this custom kernel, and you can enjoy more free time with the satisfaction of a job well done. Some people (including me) are very glad that you stepped up and helped them get a working system in the meantime. Hence... Thank you and kudos.

I'm now on daily kernel builds and resume is working, maybe not completely (time will tell) but at least sometimes.

**Comment by JHirte** [comment]
This is fixed with the latest dc-patch-bomb (DC Patches Nov 23, 2017), although it's not mentioned as fix for this explicitly.

**Comment by M-Bab** [comment]
Thats great to hear! But is it pushed already?

**Comment by mezcalbert** [comment]
This issue is solved with 4.15-rc2 !!! Finally ! 

Hooray!

**Comment by M-Bab** [comment]
And in amd-staging-drm-next as well. I will release a new kernel soon (was on business trip the past 14 days).

**Comment by M-Bab** [comment]
Should be fixed with the latest kernel,

**Comment by M-Bab** [comment]
VBlank issue is now officially fixed but locking the screen can still result in troubles (unresponsive system, screen flickering). Please report here if you have similar issues.

**Comment by mezcalbert** [comment]
Actually, I thought it was gone but it is still happening. A bit less frequently though, as I can now sometimes resume for a few days before it happens.

**Comment by M-Bab** [comment]
Related bug reports:
https://bugs.freedesktop.org/show_bug.cgi?id=105018
https://bugs.freedesktop.org/show_bug.cgi?id=101580

**Comment by mezcalbert** [comment]
I have successfully suspended and resumed for the last 6 times over the course of an ongoing 9 days of uptime. It had been a very long time I was able to for such a long period.
I will keep monitoring this, and especially with 4.17-rc1 whenever the next freeze occurs, but I'm a bit more optimistic for once.

**Comment by mezcalbert** [comment]
This is looking really good now for me. Still with 4.16.0/1+ (don't recall and not in front of me right now) and 15 days of uptime with a dozen suspending/resuming not leading to any freeze.

Last time I switched input channel of the AV receiver to TV and back, it didn't even terminate my Gnome session.
I suggest those experiencing this issue to try again with turning on/off screen or locking and give some feedback.

**Comment by M-Bab** [comment]
Can confirm the suspend issue seems to be gone.
Screen lock can still kill the system, compare https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/55
