### ISSUE TITLE
Color gets darker after instaling  kerner

### ISSUE THREAD

**Issue by NaGeL182** [M-Bab/linux-kernel-amdgpu-binaries#49]
Hello!

I installed your kernel and it solved my HDMI audio problem with my AMD RX 480, so thanks for that!

but for some reason, after I log in, ALL colors gets darker for me making some app unusable... before login everything is good it seems but after login...
why is this?

```
>screenfetch                                    
                                       nagel@nagel
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Mint 18.3 sylvia
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 4.16.0-rc5+
 MMd      /++                -sNMd:    Uptime: 1m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 2337
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: zsh 5.1.1
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 3840x1093
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 3.6.7
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme: Adapta-Nokto (Adapta-Nokto)
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme: Adapta-Nokto [GTK2/3]
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme: Mint-Y
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Noto Sans 9
      -dMNs-``-::::-------.``    dMM   CPU: Intel Core i5-6600K CPU @ 3.9GHz
       `/dMNmy+/:-------------:/yMMM   GPU: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.25.0 / 4.16.0-rc5+, LLVM 5.0.1)
          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM: 1901MiB / 15983MiB
             \.MMMMMMMMMMMMMMMMMMM   ```

**Comment by CRTX** [comment]
Something to do with the display configuration. My computer froze one time and after I rebooted it I think some file got corrupted and when I turned it back on my screen wasn't dark anymore. I would just wait for another update though, it's definitely a bug.

**Comment by m-r-s** [comment]
Here (HP ENVY x360 - 15-bq102ng) the brightness is low and cannot be changes anymore.

**Comment by M-Bab** [comment]
Is this fixed with rc6+ as well (like the other brightness issues)?

**Comment by NaGeL182** [comment]
updated to the latest kernel (4.16.0-rc7+) the issue still persist..

i usd the command `sudo dpkg -i *.deb`  and in the middle of the instalation it ask me if i want to abort it. is that normal?

**Comment by CRTX** [comment]
@NaGeL182  only install the UBUNTU ones + firmware if you have Ubuntu or the non-ubuntu `deb`s if you have another distro

**Comment by M-Bab** [comment]
Did you try the mainline kernel builds for comparison? http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16/

**Comment by NaGeL182** [comment]
so I just tried right now with the latest kernels, and the problem persists, so I tried the mainline kernels suggested by M-bab and the 4.16 works fine! even the HDMI audio works! So that kinda solved my problem.

**Comment by M-Bab** [comment]
Should be fixed now. Can you test again?

**Comment by HiDef888** [comment]
I added your kernel and it fixed my gpu issues, 2200g but I got screen darkening and it broke my VMs. 
I was running 4.16.1 prior.

**Comment by M-Bab** [comment]
I think these 3 issues are related:
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/49
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/51
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/53

So far I can't reproduce any of them so it is hard for me to help here.

**Comment by stefanheijnen** [comment]
It is fixed in 4.17rc2

Please see https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Linux-4.17-Fixes

**Comment by CRTX** [comment]
^Although that's true (I'm on 4.17rc2) I still get random freezes, in fact more than 4.16 mainline unfortunately... There's 0 errors in kern.log or dmesg, quite frustrating :(

P.S. You should probably close this as the fix is here:

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.17-rc2/

**Comment by stefanheijnen** [comment]
Sometimes I can ssh in after a freeze and most of the time dmesg shows:

```
[57437.234019] [drm] SADs count is: -2, don't need to read it
[57602.974807] vboxpci: freeing IOMMU domain 000000007b82ce92
[58925.595725] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595734] amdgpu 0000:38:00.0:   at page 0x000000010ba29000 from 27
[58925.595738] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00101031
[58925.595747] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595751] amdgpu 0000:38:00.0:   at page 0x000000010ba2b000 from 27
[58925.595755] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595764] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595767] amdgpu 0000:38:00.0:   at page 0x000000010ba14000 from 27
[58925.595770] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595778] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595782] amdgpu 0000:38:00.0:   at page 0x000000010ba12000 from 27
[58925.595785] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595793] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595796] amdgpu 0000:38:00.0:   at page 0x000000010ba10000 from 27
[58925.595799] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595807] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595810] amdgpu 0000:38:00.0:   at page 0x000000010ba21000 from 27
[58925.595813] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595821] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595824] amdgpu 0000:38:00.0:   at page 0x000000010ba23000 from 27
[58925.595827] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595835] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595838] amdgpu 0000:38:00.0:   at page 0x000000010ba0e000 from 27
[58925.595841] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595849] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595852] amdgpu 0000:38:00.0:   at page 0x000000010ba25000 from 27
[58925.595855] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58925.595863] amdgpu 0000:38:00.0: [gfxhub] VMC page fault (src_id:0 ring:24 vmid:1 pasid:32768)
[58925.595866] amdgpu 0000:38:00.0:   at page 0x000000010ba27000 from 27
[58925.595869] amdgpu 0000:38:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[58935.775096] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, last signaled seq=1071134, last emitted seq=1071136
[58935.775102] [drm] No hardware hang detected. Did some blocks stall?
```

**Comment by M-Bab** [comment]
Can you recheck with 4.17?
