### ISSUE TITLE
Occasional full screen flickering with kernel 4.16

### ISSUE THREAD

**Issue by M-Bab** [M-Bab/linux-kernel-amdgpu-binaries#50]
For me kernel 4.16 introduced a rare and random full screen black flickering. Please comment if you experience similar issues.

**Comment by mezcalbert** [comment]
I also have this. 
It is reported here. 
https://bugs.freedesktop.org/show_bug.cgi?id=105530

Although it probably isn't Raven Ridge specific.

**Comment by aubade** [comment]
I'm experiencing this or something like it on an R9 285 2Gb card.

**Comment by M-Bab** [comment]
Flickering is still present in my most recent build. It is not related to the bug https://bugs.freedesktop.org/show_bug.cgi?id=105530 .

**Comment by mezcalbert** [comment]
It is related. 
It might not be due to TearFree (the bug report is too specific and it's not just Raven Ridge) but it's the same sort of flickering/artifacts. I've read through different forums or bug reports (phoronix, here, freedesktop) that users are affected by this flickering for around 3-4 weeks now. And I am as well.

There's just no real overall bug report yet encompassing all the hardware impacted and describing it on a higher level.

**Comment by digitalgutenberg** [comment]
I can confirm getting random screen flashes on my RX 580, so I'm going to use 4.15.4+ for now. Seems as if lots of people are seeing this, it was discussed on Reddit: https://www.reddit.com/r/linux/comments/88wm3e/linux_416_released/

**Comment by M-Bab** [comment]
Can confirm it happens with the official 4.16 kernel as well. This is awful overall but nice to hear it is not specifically this kernel :-). I am optimistic the AMD developers will figure it out soon.

**Comment by M-Bab** [comment]
Related bug reports:
https://bugzilla.kernel.org/show_bug.cgi?id=199101
https://bugs.freedesktop.org/show_bug.cgi?id=105530
https://bugs.freedesktop.org/show_bug.cgi?id=105083
Possibly related:
https://bugs.freedesktop.org/show_bug.cgi?id=105300
https://bugs.freedesktop.org/show_bug.cgi?id=102646

**Comment by M-Bab** [comment]
" Harry Wentland 2018-04-06 14:15:18 UTC
We reproduced the issue and have someone looking into it."

I expect this to be fixed soon.

**Comment by markathomas** [comment]
Thanks for investigating; I just booted into 4.16 and am experiencing this issue as well.  Glad to know someone's on it already.

**Comment by M-Bab** [comment]
Is fixed now. Hell that was annoying.

**Comment by obrotowy** [comment]
lol it isn' t fixed, still have this issue on 4.16.2 with R9 380.

**Comment by chewi** [comment]
The "fix" didn't make it into 4.16.2. It's also not a fix as such. You need to revert torvalds/linux@cd2d6c92a8e39d7e50a5af9fcc67d07e6a89e91d and torvalds/linux@36cc549d59864b7161f0e23d710c1c4d1b9cf022.

**Comment by M-Bab** [comment]
@SynneK1337 So you installed one of the 4.16.2+_18.04.**13** kernels and it did not fix the issue?

**Comment by chewi** [comment]
To clarify, I'm not using Debian/Ubuntu so I was just using this information to build my own kernel. Reverting those commits fixed it for me.

**Comment by M-Bab** [comment]
Yes, it is not included in the official 4.16.2 but the reverts are already in my 4.16.2+_18.04.13 kernel:
https://github.com/M-Bab/linux-kernel-amdgpu/commit/fc0644eddd2d5f77aac44ad2ab5a3edae08d11c2
https://github.com/M-Bab/linux-kernel-amdgpu/commit/01a61cd8a5bcbe1ebce59417d8c0cd3b34157d25

**Comment by inferrna** [comment]
Affecting me to. Just rebooted from 4.15.13 to 4.16.2 vanilla kernel.
rx560 + mesa 17.3 + ubuntu 16.04

**Comment by relm** [comment]
Thanks for linking the reverts, that fixed it for me. Running a WX 7100 here.
