### ISSUE TITLE
More gamma woes

### ISSUE THREAD

**Issue by aubade** [M-Bab/linux-kernel-amdgpu-binaries#51]
I've just updated to the latest kernel+firmware debs, and they've improved a fair bit in most places, except I'm experiencing some really strange gamma issues. Color correction is properly applied to red green and blue channels, unless that channel is at 255, at which point it's left uncorrected. This means that bright areas stay extremely bright and their hues distort wildly if a lot of darkening is applied. (for example using f.lux or redshift)

I'm attaching a couple photos showing what my desktop looks like at xgamma -gamma 1.0 (normal) and xgamma -gamma 0.1)
![20180330_212143](https://user-images.githubusercontent.com/436747/38158378-0c52ae46-3461-11e8-8dd5-148f6d31dd93.jpg)

![20180330_212134](https://user-images.githubusercontent.com/436747/38158380-15bb0da2-3461-11e8-8fe0-1d86bd1898d8.jpg)

**Comment by aubade** [comment]
(Incidentally, This distortion persists when I ctrl-alt-F1 to the console, which is why I believe it's lower-level in the driver and probably not an Xorg driver issue)

**Comment by CRTX** [comment]
Kernel 4.16 final release is today. Going to wait for the new binaries to sort the gamma issues out... I hope!

**Comment by M-Bab** [comment]
Is the regression resolved? Does it also appear with the mainline kernel builds (http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16/)?

**Comment by aubade** [comment]
Okay, unfortunately I experience the problem on both the AMDGPU and Mainline 4.16 kernels.

**Comment by aubade** [comment]
Unfortunately, the problem still happens in the new 4.16.0 build, and in the upstream 4.16 build.

**Comment by CRTX** [comment]
I'm using wayland (haven't tested xorg) but my gamma and brightness issues have been resolved on an HP Envy 15z with Ryzen 2500U APU

**Comment by M-Bab** [comment]
Such bugs in a release kernel is pretty sad. Looks like 4.16 is among the worst amdgpu kernels so far.

**Comment by M-Bab** [comment]
Should be fixed now. Can you test again?

**Comment by aubade** [comment]
Unfortunately, I still have the problem. It's subtly different (not ~just~ affecting channels at 255), but it's still missing those bright channels. Another photo of my monitor at xgamma -gamma 0.1
![20180413_142620](https://user-images.githubusercontent.com/436747/38751792-252cea14-3f27-11e8-9745-3c47ee36bfaf.jpg)

**Comment by aubade** [comment]
It might be fixed. (setting gamma to 0.1 looks odd, but it looks the same on my intel laptop. I'll have to wait until Redshift engages to see if things still look messed up there)

**Comment by aubade** [comment]
Okay, it definitely still is messed up. I took some pictures comparing my desktop's R9 285 output with my laptop's Intel E8000 output. The laptop's panel is inherently cooler-colored than my desktop LCD, but I think the issue is still visible.
Laptop (correct):
![20180413_203339](https://user-images.githubusercontent.com/436747/38762529-c5d5f16c-3f5a-11e8-8649-03ff4c5f7c9e.jpg)
![20180413_203530](https://user-images.githubusercontent.com/436747/38762531-cf8d19f6-3f5a-11e8-83d5-3ae97e99823c.jpg)
Desktop (wrong):
![20180413_203331](https://user-images.githubusercontent.com/436747/38762537-dc534e58-3f5a-11e8-83a8-78cc16a08594.jpg)
![20180413_203457](https://user-images.githubusercontent.com/436747/38762543-e5f0b3f6-3f5a-11e8-968c-d15b331ff5d5.jpg)
Note especially the sharp edge of the shadow on the Ubuntu-MATE logo and odd lilac-colored post infobar on the Github shot.

**Comment by M-Bab** [comment]
I think these 3 issues are related:
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/49
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/51
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/53

So far I can't reproduce any of them so it is hard for me to help here.

**Comment by M-Bab** [comment]
Can you recheck with 4.17?

**Comment by M-Bab** [comment]
Do the problems of this issue still exist?
